### ISSUE TITLE
adata.to_backed() as the opposite of adata.to_memory() 

### ISSUE THREAD

**Issue by JackSSK** [scverse/anndata#1246]
Would it be possible to have an opposite method of to_memory() that release arrays from memory and put them backed?
Any recommendation on work-arrounds other than total release the object and load file again with backed = True is appreciated!

**Comment by flying-sheep** [comment]
This already exists! https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.filename.html

I wonder why `to_memory` exists though.

**Comment by JackSSK** [comment]
Thanks a lot for your reply!
But unfortunately adata.filename is kinda different I suppose. 
For example, after I load in the data and filter out some cells and genes with qc protocols, if I use 
>> adata.filename = 'process.h5ad'
the processed data will actually be stored in the new 'process.h5ad' file instead of original unprocessed data file right.
And if I set filename to the original unprocessed data file, the data storing there would be changed.
Would that be possible to, in this case, set processed data to backed while not changing original file nor making temporary file?

**Comment by JackSSK** [comment]
btw I am using Version: 0.10.3

**Comment by flying-sheep** [comment]
> And if I set filename to the original unprocessed data file, the data storing there would be changed.

I guess that’s

**Comment by ivirshup** [comment]
I don't think `.to_memory` is really the opposite of `.to_backed` since `.to_memory` will also bring lazy arrays into memory, which may not be based on an on disk implementation.

I would also generally be against adding more features onto backed mode, since most of it's functionality is now available in more generic formats.

@JackSSK, you could do something like:

```python
import anndata as ad

adata = ad.read_h5ad(path_to_h5ad)
some_func(adata)  # Whatever processing needed X

f = h5py.File(path_to_h5ad)  # Open dataset
adata.X = ad.experimental.sparse_dataset(f["X"])  # Re-assign X
```

Which will drop `X` from memory and replace it with the backed array.

We can't just reset `X` to refer to the matrix from the file, since we have no way of knowing if you've modified the in-memory matrix. E.g. we can't promise the data will be the same.

**Comment by ivirshup** [comment]
I'm going to close this as not planned in its current formulation. I think we've demonstrated how this can be done with the existing implementation.
