### ISSUE TITLE
`io` submodule

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1681]
### Please describe your wishes and possible alternatives to achieve the desired result.

We should have a public submodule `io` since we're starting to grow our IO api.

This should include all public methods related to `io`, including:

* `read_elem`, `write_elem`
* `sparse_dataset`

Eventually I would also like whatever public API we have for the registries to be included here.

I think it would make sense to put some of the more esoteric reader functions in here, like `read_text`, `read_loom`, etc. However, I'm not so sure about `read_h5ad`, `read_zarr`. I think these could be exported from both the main namespace and `io`, but am not 100% sure on this.

**Comment by flying-sheep** [comment]
> I'm not so sure about `read_h5ad`, `read_zarr`.

If you’re unsure because you don’t know how to categorize these, I think I can help: Those are the lossless formats, whereas the others are approximate formats that don’t support all of an AnnData object’s features. I already added some docs in a recent PR to distinguish the two tiers of format support.

One alternative would be to have only one `read` method in the root like `def read(path: Path, *, format: Literal['zarr', ...] | None = None)` which would be used when people just want to read one of the lossless formats without options.
