### ISSUE TITLE
Add whitelist when writing in backed mode to same file

### ISSUE THREAD

**Issue by joshua-gould** [scverse/anndata#197]
Use case: I have a large anndata file that has many fields in obs, obsm, and uns. I open the file in backed mode and add one field to obsm. Saving the file takes forever because anndata is writing all fields, even ones that are unchanged.

**Comment by ivirshup** [comment]
I'm looking to add a method `update` (as opposed to `write`) which should be closer to this. The difficult part is figuring out what has changed and what hasn't. I think this might have to be user defined for the current backed API. So you would write something like: `adata.update("obsm")` or maybe `adata.update(pth, {"obsm": "obsm_key"})`.

**Comment by ivirshup** [comment]
This is currently achievable with `write_elem`.

Being able to do an update with the current backed mode would require being able to know which elements were modified and which weren't... which is probably out of scope.

We could maybe do this with dask backed arrays, since we can check if their graph simplifies to "read in".

**Comment by ivirshup** [comment]
I'm going to close this particular issue since I think the scope of "whitelist" is accomplished by `write_elem`
