### ISSUE TITLE
Calling write_h5ad without converting strings to categoricals

### ISSUE THREAD

**Issue by ljjh20** [scverse/anndata#534]
Hi AnnData team,

It seems I am unable to write to h5ad without having `strings_to_categoricals` be called. 
https://github.com/theislab/anndata/blob/dad9a085afdfb8d23b30cbbbe890acffdae4d621/anndata/_io/h5ad.py#L85

I am using the output h5ad file in Java, not with scanPy, so having my string data encoded as categoricals causes me a lot of problems. Would it be possible to make this optional? 

Thanks!

**Comment by ivirshup** [comment]
Related: https://github.com/theislab/scanpy/issues/1747

I think I'd be fine with a keyword argument for this.

Since it's significantly faster to use the categoricals so we'd probably stick with that for the default. There should be categorical style arrays available in java though, Arrow dictionary encoded arrays for example.

**Comment by adamgayoso** [comment]
I don't see why this should be default, even if it makes things faster in scanpy it can happen at any time (not strictly at saving) and every subsequent call will be a no-op basically

**Comment by falexwolf** [comment]
Suggestion: https://github.com/scverse/anndata/pull/1474

**Comment by flying-sheep** [comment]
Fixed by #1474
