### ISSUE TITLE
Trying to run DCA on microbiome dataset

### ISSUE THREAD

**Issue by ajlee21** [scverse/anndata#599]
I'm attempting to run your DCA method on microbiome data containing 11K rows (samples) x 1200 columns (microbes). 

In trying to read in the data using io.py `read_dataset()` I get the following error which can be traced back `anndata.py`

The error message is:

```pytb
~/anaconda3/envs/common_microbe/lib/python3.7/site-packages/anndata/_core/anndata.py in _check_dimensions(self, key)
   1834         if "var" in key and len(self._var) != self._n_vars:
   1835             raise ValueError(
-> 1836                 "Variables annot. `var` must have number of columns of `X`"
   1837                 f" ({self._n_vars}), but has {self._var.shape[0]} rows."
   1838             )

ValueError: Variables annot. `var` must have number of columns of `X` (1232), but has 7391 rows.
```

Any help with how to apply DCA to a dataframe like this would be helpful. Thank you!

**Comment by flying-sheep** [comment]
Hi! Sorry for not responding back then. `read_dataset` isn’t an exported function of anndata, or is it?

If you happen to have the file around still, please post the code that led to the error and upload/link to the file so we can reproduce.

I’m going to close this because it hasn’t come up anymore. I’ll reopen if it’s still an issue.
