### ISSUE TITLE
0.9.0 on Windows: KeyError: "Unable to open object (object 'anno1' doesn't exist)"

### ISSUE THREAD

**Issue by sir-sigurd** [scverse/anndata#969]
Our test CI job on Windows started to fail with release of anndata 0.9.0:
https://github.com/quiltdata/quilt/actions/runs/4666597638/jobs/8261488713

Linux jobs are still fine.

I can try to provide minimal example for repro if it's needed.

**Comment by Koncopd** [comment]
@sir-sigurd , looks like this problem https://github.com/scverse/anndata/issues/956
It was fixed here https://github.com/scverse/anndata/pull/958, but i don't see that this PR was merged in 0.9.0 https://github.com/scverse/anndata/tree/0.9.0

@ivirshup, can we have a 0.9.1release with this PR included, because now the release is broken on Windows.

**Comment by ivirshup** [comment]
Just started a backport

**Comment by ivirshup** [comment]
Fixed by: https://github.com/scverse/anndata/pull/973
